//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClassRoomHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TargetDir {
            get {
                return ((string)(this["TargetDir"]));
            }
            set {
                this["TargetDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DesktopTool_AutoShow {
            get {
                return ((bool)(this["DesktopTool_AutoShow"]));
            }
            set {
                this["DesktopTool_AutoShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DesktopTool_ShowCalc {
            get {
                return ((bool)(this["DesktopTool_ShowCalc"]));
            }
            set {
                this["DesktopTool_ShowCalc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DesktopTool_ShowScissors {
            get {
                return ((bool)(this["DesktopTool_ShowScissors"]));
            }
            set {
                this["DesktopTool_ShowScissors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UMgr_Enabled {
            get {
                return ((bool)(this["UMgr_Enabled"]));
            }
            set {
                this["UMgr_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UMgr_ShowDialog {
            get {
                return ((bool)(this["UMgr_ShowDialog"]));
            }
            set {
                this["UMgr_ShowDialog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AllException")]
        public global::ClassRoomHelper.Library.DebugLevel DebugLevel {
            get {
                return ((global::ClassRoomHelper.Library.DebugLevel)(this["DebugLevel"]));
            }
            set {
                this["DebugLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugEnabled {
            get {
                return ((bool)(this["DebugEnabled"]));
            }
            set {
                this["DebugEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Daily")]
        public global::ClassRoomHelper.Library.Services.ResortMode ResortMode {
            get {
                return ((global::ClassRoomHelper.Library.Services.ResortMode)(this["ResortMode"]));
            }
            set {
                this["ResortMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool StartAfterWindows {
            get {
                return ((bool)(this["StartAfterWindows"]));
            }
            set {
                this["StartAfterWindows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstUse {
            get {
                return ((bool)(this["FirstUse"]));
            }
            set {
                this["FirstUse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Never")]
        public global::ClassRoomHelper.Library.Services.CleanMode CleanMode {
            get {
                return ((global::ClassRoomHelper.Library.Services.CleanMode)(this["CleanMode"]));
            }
            set {
                this["CleanMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool VoiceNameCallOut {
            get {
                return ((bool)(this["VoiceNameCallOut"]));
            }
            set {
                this["VoiceNameCallOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameCallOutPre {
            get {
                return ((string)(this["NameCallOutPre"]));
            }
            set {
                this["NameCallOutPre"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("同学 , 请回答问题")]
        public string NameCallOutPost {
            get {
                return ((string)(this["NameCallOutPost"]));
            }
            set {
                this["NameCallOutPost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DesktopTool_ShowNameSelector {
            get {
                return ((bool)(this["DesktopTool_ShowNameSelector"]));
            }
            set {
                this["DesktopTool_ShowNameSelector"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Copy")]
        public global::ClassRoomHelper.Library.Services.FileExistedSolution FileExistedSolution {
            get {
                return ((global::ClassRoomHelper.Library.Services.FileExistedSolution)(this["FileExistedSolution"]));
            }
            set {
                this["FileExistedSolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ALL")]
        public global::ClassRoomHelper.Library.Services.CollectMode CollectMode {
            get {
                return ((global::ClassRoomHelper.Library.Services.CollectMode)(this["CollectMode"]));
            }
            set {
                this["CollectMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200, 200")]
        public global::System.Drawing.Point HelperWindowLocation {
            get {
                return ((global::System.Drawing.Point)(this["HelperWindowLocation"]));
            }
            set {
                this["HelperWindowLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowHelperWindow {
            get {
                return ((bool)(this["ShowHelperWindow"]));
            }
            set {
                this["ShowHelperWindow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300, 300")]
        public global::System.Drawing.Point DesktopToolLoc {
            get {
                return ((global::System.Drawing.Point)(this["DesktopToolLoc"]));
            }
            set {
                this["DesktopToolLoc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("高考")]
        public string Timer_EventName {
            get {
                return ((string)(this["Timer_EventName"]));
            }
            set {
                this["Timer_EventName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Timer_Enabled {
            get {
                return ((bool)(this["Timer_Enabled"]));
            }
            set {
                this["Timer_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2020-06-07")]
        public global::System.DateTime Timer_Date {
            get {
                return ((global::System.DateTime)(this["Timer_Date"]));
            }
            set {
                this["Timer_Date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WallpaperEngine_Enabled {
            get {
                return ((bool)(this["WallpaperEngine_Enabled"]));
            }
            set {
                this["WallpaperEngine_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BugFixForSeewo {
            get {
                return ((bool)(this["BugFixForSeewo"]));
            }
            set {
                this["BugFixForSeewo"] = value;
            }
        }
    }
}
